version: '3.8'
services:

  db:
    image: postgres:15
    container_name: court-booking-db
    restart: always
    environment:
      POSTGRES_DB: court_booking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "3306:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  myadmin:
    image: adminer
    container_name: court-booking-myadmin
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "3310:8080"
    depends_on:
      - db

volumes:
  db_data:
